// <auto-generated />
using EmployeeApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612065047_ÜpdatingFKRenamingFk")]
    partial class ÜpdatingFKRenamingFk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeApp.Api.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 101,
                            DepartmentName = "IT",
                            Location = "Bangalore"
                        },
                        new
                        {
                            DepartmentId = 102,
                            DepartmentName = "Sales",
                            Location = "Chennai"
                        },
                        new
                        {
                            DepartmentId = 103,
                            DepartmentName = "HR",
                            Location = "Pune"
                        },
                        new
                        {
                            DepartmentId = 104,
                            DepartmentName = "Payroll",
                            Location = "Trivandrum"
                        });
                });

            modelBuilder.Entity("EmployeeApp.Api.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            DeptId = 101,
                            Gender = "Female",
                            Name = "Mary",
                            Salary = 78000m
                        },
                        new
                        {
                            Id = 2,
                            Age = 26,
                            DeptId = 102,
                            Gender = "Male",
                            Name = "Arun",
                            Salary = 45000m
                        },
                        new
                        {
                            Id = 3,
                            Age = 29,
                            DeptId = 103,
                            Gender = "Female",
                            Name = "Shivani",
                            Salary = 87000m
                        },
                        new
                        {
                            Id = 4,
                            Age = 33,
                            DeptId = 101,
                            Gender = "Male",
                            Name = "Manu",
                            Salary = 67000m
                        });
                });

            modelBuilder.Entity("EmployeeApp.Api.Models.Employee", b =>
                {
                    b.HasOne("EmployeeApp.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
